#!/usr/bin/env python3

"""
GTG stress test
"""
import sys
import dbus
import uuid

def connect():
    # We will connect on the session bus
    bus = dbus.SessionBus()
    liste = bus.list_names()
    busname = "org.gnome.GTG"
    remote_object = bus.get_object(busname,"/org/gnome/GTG")
    return dbus.Interface(remote_object,dbus_interface="org.gnome.GTG")

if __name__ == '__main__':
    if len(sys.argv) == 1:
         print("Usage: " + sys.argv[0] + " <number-of-tasks> [number-of-words-in-bodies]")
         sys.exit(1)
    total_tasks = int(sys.argv[1])

    text_length = 0
    if len(sys.argv) > 2:
        text_length = int(sys.argv[2])

    gtg = connect()
    for i in range(total_tasks):
        lengthy_text = ""
        for i in range(text_length):
            lengthy_text += str(uuid.uuid4())
        gtg.NewTask("Active", str(uuid.uuid4()), '', '', '', [], lengthy_text, [])
